spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/finwiz  
    username: postgres                         
    password: postgres                        

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect  s
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
      ddl-auto: update
    show-sql: true

server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
