spring:
  application:
    name: budget-service

  datasource:
    url: jdbc:postgresql://localhost:5432/finwiz  
    username: postgres                         
    password: postgres                         
    driver-class-name: org.postgresql.Driver   

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect  
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
      ddl-auto: update
    show-sql: true

server:
  port: 8003
